---
  version: '3.6'

  secrets:
    tomcat_ssl_crt:
      file: ./docker/certificates/tomcat/tomcat-wildcard-dev.crt
    tomcat_ssl_key:
      file: ./docker/certificates/tomcat/tomcat-wildcard-dev.key
    oauth_sign_crt:
      file: ./docker/certificates/oauth2/oauth2-wildcard-dev.crt
    oauth_sign_key:
      file: ./docker/certificates/oauth2/oauth2-wildcard-dev.key

  services:
    waterauth:
      container_name: waterauth
      build: 
        context: .
        args:
          # the -D option supresses INFO-level logs about dependency downloads. This enables the build to finish within Travis' log length limit.
          # The -P option skips the dependency security check in favor of build stability -- the official NVD server is rate-limited, and external builds lack access to our internal NVD mirror
         BUILD_COMMAND: 'mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean verify -P=!dependency-security-check'
      image: water-auth-server
      ports:
        - "8443:8443"
      secrets:
        - source: tomcat_ssl_crt
          target: /home/spring/tomcat-wildcard-ssl.crt
        - source: tomcat_ssl_key
          target: /home/spring/tomcat-wildcard-ssl.key
        - source: oauth_sign_crt
          target: /home/spring/oauth-wildcard-sign.crt
        - source: oauth_sign_key
          target: /home/spring/oauth-wildcard-sign.key
      env_file:
        - docker/config.env
        - docker/secrets.env
